### PR TITLE
[TESTED] Performance fix 

### PR DESCRIPTION
**Pull request by PermissionError**
After surfing the net about the issue that SQLite3 made my pmmp Server 3000 time laggier, I've decided to look in the code. I have changed 1 line of code, turning the sync off in the database. Would it work?
(nub at php)

NEEDS TESTING

### CODE REVIEW

**Comment by PatheticMing** [comment]
Are you querying like over 10000+ blocks?

**Comment by PermissionError** [comment]
Nope, it just  lags when I have 10+ players on building at the same time
I'm pretty sure it's the SQLite database

**Comment by PermissionError** [comment]
Just tested it by querying over 5000 blocks, quite fine, almost no lag.

**Comment by PermissionError** [comment]
Stress tested with 40+ players on at the same time. No lag at all.

**Comment by PermissionError** [comment]
@XdmingXD Have you made a decision?

**Comment by PatheticMing** [comment]
@TBNRShadowDev  I am still a student and I am very busy
Also, there are other stuff waiting for me to do 
Developing this plugin isn't my only job
So please wait patiently

**Pull request closed without merging**
